### ISSUE TITLE
ダークモードをOFFにしたときの挙動について

### ISSUE THREAD

**Issue by KomeijiKaede** [tomacheese/watch-twitter-likes#78]
誰がいいねしたかの文字は色が切り替わるのに対して、画像にオーバーレイされているbackground-image: linear-gradientの色が暗いままなので文字が見づらいかも  
また、背景色(白)に対してのコントラストが高すぎて違和感があるので
```css
background-image: linear-gradient(rgba(255, 255, 255, 0.1), rgba(255, 255, 255, 0.5))
```
とかにするといいかもしれません

**Comment by book000** [comment]
:thinking:

![image](https://user-images.githubusercontent.com/8929706/208111510-1e4b45ce-cca3-41b9-a330-fdfb98348135.png)
